### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by ruida** [NExT-ChatV/NExT-Chat#12]
Hi, 

I start the training with run_stage1.sh.   One error message comes up when saving the training model at step 3000. 
Any suggestions? 

Thanks, 

--Ruida

tensor(0., device='cuda:1', grad_fn=<MeanBackward0>)
^M  1%|          | 2998/298104 [2:14:08<221:28:49,  2.70s/it]tensor(0.0031, device='cuda:1', grad_fn=<MeanBackward0>)
tensor(0., device='cuda:0', grad_fn=<MeanBackward0>)
^M  1%|          | 2999/298104 [2:14:11<222:10:07,  2.71s/it]tensor(0.0236, device='cuda:0', grad_fn=<MeanBackward0>)
tensor(0.0002, device='cuda:1', grad_fn=<MeanBackward0>)
^M  1%|          | 3000/298104 [2:14:14<222:58:27,  2.72s/it]^M                                                           ^M{'loss': 12.1835, 'learning_rate': 6.7084078711985685e-06, 'epoch': 0.02}
^M  1%|          | 3000/298104 [2:14:14<222:58:27,  2.72s/it][INFO|trainer.py:2807] 2024-01-29 13:30:51,045 >> Saving model checkpoint to ./output/stage1/checkpoint-3000
[INFO|configuration_utils.py:458] 2024-01-29 13:30:51,047 >> Configuration saved in ./output/stage1/checkpoint-3000/config.json
[INFO|configuration_utils.py:375] 2024-01-29 13:30:51,048 >> Configuration saved in ./output/stage1/checkpoint-3000/generation_config.json
[INFO|modeling_utils.py:1859] 2024-01-29 13:31:01,586 >> The model is bigger than the maximum size per checkpoint (10GB) and is going to be split in 3 checkpoint shards. You can find where each parameters has been saved in the index located at ./output/stage1/checkpoint-3000/pytorch_model.bin.index.json.
[INFO|tokenization_utils_base.py:2210] 2024-01-29 13:31:01,586 >> tokenizer config file saved in ./output/stage1/checkpoint-3000/tokenizer_config.json
[INFO|tokenization_utils_base.py:2217] 2024-01-29 13:31:01,631 >> Special tokens file saved in ./output/stage1/checkpoint-3000/special_tokens_map.json
[INFO|tokenization_utils_base.py:2267] 2024-01-29 13:31:01,632 >> added tokens file saved in ./output/stage1/checkpoint-3000/added_tokens.json
Figure saved: ./output/stage1/trainer_state.png
Traceback (most recent call last):
  File "/data/me/NExT-Chat/mllm/pipeline/finetune.py", line 141, in <module>
    main()
  File "/data/me/NExT-Chat/mllm/pipeline/finetune.py", line 62, in main
    train_result = trainer.train()
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/transformers/trainer.py", line 1901, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/transformers/trainer.py", line 2237, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/transformers/trainer.py", line 2306, in _save_checkpoint
    save_fsdp_optimizer(
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/accelerate/utils/fsdp_utils.py", line 138, in save_fsdp_optimizer
    optim_state = FSDP.optim_state_dict(model, optimizer)
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1818, in optim_state_dict
    return FullyShardedDataParallel._optim_state_dict_impl(
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1246, in _optim_state_dict_impl
    return _optim_state_dict(
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1447, in _optim_state_dict
    fsdp_osd["param_groups"] = _unflatten_param_groups(
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1238, in _unflatten_param_groups
    nested_unflat_param_names = [
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1239, in <listcomp>
    param_to_fqns[param] for param in param_group_params
KeyError: Parameter containing:
tensor([[ 1.2517e-06, -1.7881e-06, -4.3511e-06,  ...,  8.9407e-07,
         -6.5565e-06,  8.9407e-07],
        [ 2.6588e-03, -4.0588e-03,  2.1038e-03,  ..., -9.7656e-03,
          3.4580e-03, -4.0665e-03],
        [ 1.0414e-02,  8.3237e-03, -5.6038e-03,  ...,  2.6588e-03,
         -1.3170e-03, -3.6335e-03],
        ...,
        [ 7.1006e-04,  6.8368e-04, -4.5054e-04,  ..., -4.3397e-04,
         -9.7029e-05, -4.8664e-04],
        [ 7.1006e-04,  6.8368e-04, -4.5054e-04,  ..., -4.3397e-04,
         -9.7029e-05, -4.8664e-04],
        [ 7.1006e-04,  6.8368e-04, -4.5054e-04,  ..., -4.3397e-04,
         -9.7029e-05, -4.8664e-04]], device='cuda:0', requires_grad=True)
^M  1%|          | 3000/298104 [2:14:43<220:51:57,  2.69s/it]
[2024-01-29 13:31:15,414] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2211037 closing signal SIGTERM
[2024-01-29 13:31:15,528] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2211036) of binary: /gpfs/gsfs12/users/me/conda/envs/next_chat_dist/bin/python
Traceback (most recent call last):
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/gpfs/gsfs12/users/me/conda/envs/next_chat_dist/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/data/me/NExT-Chat/mllm/pipeline/finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-29_13:31:15
  host      : cn1113.hpc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2211036)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by waxnkw** [comment]
I guess it is torch version's problem. I use "2.1.1+cu118" in my code. You can take a try for torch==2.1.1

Later, I will add a deepspeed training, which does not have the problem.

**Comment by ruida** [comment]
I switch to pytorch 2.11 + cu11.8.   The same error message.

**Comment by waxnkw** [comment]
I add the deepspeed training, where the weights will not be saved via fsdp. It may help. The instruction is [here](https://github.com/NExT-ChatV/NExT-Chat#training).

**Comment by ruida** [comment]
Thanks for the update.  I switch to the latest code release. 
In nextchat_deepspeed.py,  I change the per_device_train_batch_size from 8 to 2.  I run two A100 cards and get the running out of memory exception.   What's your card training scenario?  Thanks.

**Comment by ruida** [comment]
Sorry.  I run your deepspeed update with 4  a100 cards.   It starts running.  Thanks for the updates.
